docs/http-api.md
This is a first pass at documenting what the HTTP API looks like from an user perspective.
=> CORE-1565 HTTP API docs

package.json
Added test runner, empty test directory, and wired up 'npm run test' command.
=> Added test runner, tests dir, and test command

docs/http-api.md, lib/control/v1/core.js, test/core-api-v1.js
Implemented the Core API which includes `/v1/health` and `/v1/status` endpoints. The `Core` function assumes it's been provided an instance of the `Storage` class so it has properties to render.
=> Feature Core API

package.json
Run `npm run coverage` to generate coverage information in the `coverage/` folder.
=> Added istanbul code coverage tool

README.md, lib/source/s3.js, package.json, test/bin/s3-server.js, test/data/s3/account/12345.json, test/data/s3/ami-4aface7a.json, test/data/s3/global.json, test/data/s3/index.json
Added S3 test server for local development. See the README for information on use.
=> Added 'npm run s3-server' task

lib/source/metadata.js, test/metadata.js
Updated the metadata source so the output from the status() method is consistent with other sources.
=> Updated metadata source status() output

lib/plugin-manager.js, package.json, test/plugin-manager.js
This is the first of two pull requests for the `PluginManager`. The module is complete, however test coverage only focuses on instantiation and error conditions on startup. The next pull request will focus on testing persistent behavior such as handling events from sources and failures during operation.
=> Feature plugin manager

lib/control/v1/core.js, test/core-api-v1.js
Updates to the core API that take into account changes to the storage and plugin manager interfaces.
=> Integrate core api

bin/server.js, lib/storage.js
Hooked up plugin manager initialization.
=> Integrate components

bin/server.js
=> Fixed bug where path resolution for the config file wasn't working correctly

README.md, config/dev.json, lib/source/s3.js, package.json, test/bin/s3-server.js
This PR creates self-contained S3 and Metadata servers to mock dependencies and allow local development. Simply run `npm run dev-server` and you should be all set.
=> Feature dev server task

lib/plugin-manager.js, test/plugin-manager.js
This PR registers the Consul plugin. Right now we're registering it outside of the index loop so it will always be registered, regardless of the contents of the index.
=> Hook up Consul source plugin

lib/storage.js, test/storage-engine.js
This fixes up a couple of TODOs in the code around tests that where missing for the `clear` and `unregister` functions in the `Storage` class.
=> Fix: More Storage unregistration tests

Gemfile, README.md, Rakefile
This pull requests aims to setup a "oneliner" that can be placed on the build slaves so that we can build packages of props.d.
=> PD-6304 Add Rakefile to release/package props.d

lib/source/metadata.js, lib/source/s3.js, test/core-api-v1.js, test/plugin-manager.js, test/s3.js
Refactored a few places to make testing simpler as well.
=> Improve test coverage

README.md
This adds a "why", "what", "who" marketing blurb to the top of the README. In addition, there's a tagline that should eventually go in the GitHub repository description.
=> Feature: README marketing blurb

README.md, docs/getting-started/README.md, docs/getting-started/usage.md
This adds a "how to use propsd" section to the getting started guide. Additionally, the table of contents for the guide has been updated so it links to the individual subsections.
=> Feature: Usage guide

README.md
From the README, it's tough to understand what this thing does or what the benefits are.  Trying to simplify it without redoing everything that's on/in the gsg page.
=> Adding some more color to the README page.

Rakefile, lib/control/v1/core.js, test/core-api-v1.js
This PR adds the `version` property to the `/v1/health` endpoint which outputs the application version.
=> Feature: Add version property to health endpoint

lib/control/v1/core.js, test/core-api-v1.js
This fixes up the Core API so all its tests pass. The code has been updated so the output for `/v1/health` and `/v1/status` doesn't change.
=> Fix: Core API tests

lib/source/s3.js, test/s3.js
This fixes the S3 source tests so they all pass with the new code.
=> Fix: S3 source tests

lib/source/common.js, lib/source/metadata.js, lib/source/metadata/parser.js, lib/source/s3.js, test/lib/helpers.js, test/lib/stub/source.js, test/metadata.js, test/source-common.js
* Refactors into a base class and a polling class
* Exports factory methods to bind parsers to source classes
* Implements and tests correct inheritance checking
* Centralizes tests of the Source state-machine
=> Update source/common for Consul

lib/logger.js
This fixes #173 and removes colored output from the request logs in propsd.
=> Fix: Remove colored output from request logs

Gemfile, Gemfile.lock, Rakefile
So octokit can detect file mime type when uploading.
=> Added mime-types gem

lib/properties.js, lib/transformers/tokend-client.js, lib/transformers/tokend.js, test/tokend-client.js, test/tokend-transformer.js
This is a work in progress to fix #211 and allow us to parse transit secrets decrypted by Tokend.
=> Feature: Transit secret provider

lib/transformers/tokend.js, test/tokend-transformer.js
This PR adds functionality to the Tokend transformer to decrypt [KMS encrypted secrets](https://github.com/rapid7/tokend/pull/99).
=> Implemented tokend transformer for KMS encrypted secrets.

cookbook/recipes/default.rb
This PR changes the desired ownership of the Propsd installation and conf dir so that it's owned by the installing user (e.g. `root`) but still run by the Propsd user.
This resolves #230.
=> Reduce Propsd user privileges

lib/source/metadata.js, lib/source/metadata/parser.js, lib/source/metadata/util.js, lib/sources/iindex.js, package.json, test/metadata.js, yarn.lock
=> Fix metadata failure crashing process
