- docs/http-api.md
- lib/control/v1/conqueso.js
- package.json
- test/conqueso-api-v1.js
This sets up the [Conqueso compatibility layer](https://github.com/rapid7/propsd/blob/feature-conqueso-api/docs/http-api.md#conqueso) for the HTTP API.
The `Conqueso` function assumes it's been provided an instance of the `Storage` class so it has properties to render. My current assumption is that the Storage class takes care of flattening properties, so accessing the `.properties` value returns a POJO of key value pairs.
The HTTP `OPTIONS` method is now supported and the documentation's been updated to reflect that. I'm contemplating supporting `HEAD` as well (since we support `GET`). Though I don't think that's necessary for Conqueso compatibility.
> Feature Conqueso API

- lib/logger.js
- test/logger.js
This fixes and issue where the logger would crash if you attempt to instantiate it without a config file.
> Fix logger without file

- docs/class-storage.md
- lib/storage.js
- test/storage-engine.js
This provides a `Storage` class to manage the collected set of merged properties from plugins. The `Storage#register` function is called to register plugins. When a plugin has updated properties, calling `Storage#update` to let the engine know new properties are available.
The responsibility for registering plugins with the `Storage` class and notifying the `Storage` class when plugins have new properties, is left to up an as of yet undefined `PluginManager`.
> Feature storage engine

- lib/source/metadata.js
```javascript
// Storage.register
register(plugin) {
if (canMerge(plugin) && plugin.hasOwnProperty('properties')) {
this.sources.push(plugin);
}
}
```
The `Metadata` source can't be registered with the storage layer because getters aren't picked up by `hasOwnProperty()`. We could change the storage layer, but `Object.getOwnPropertyDescriptor()` is inconsistent when the underlying data comes from an object with a different `__proto__`.
It's easier and more consistent to have a properties attribute on the `Metadata` class rather than use a getter.
> Fix for the metadata source plugin not playing nice with the storage layer's register method

- lib/source/metadata.js
- test/metadata.js
This fixes a bug where even if a metadata source plugin instance is shut down it still maintains the sha1 signature of the data which means `update` events won't be emitted if the plugin is started again unless the underlying data changes.
> Fix metadata signature bug

- docs/sources/source-interface.md
- lib/source/metadata.js
- lib/source/s3.js
- test/metadata.js
- test/s3.js
This is the first pull request that will culminate in the `PluginManager` implementation. The `PluginManager` requires a defined `type` for each source in order to create an instance of the correct source plugin from the index.
This should be an essentially static property per source class. The value of `type` should be reflected in the `_registerSources()` method in the `PluginManager`.
> Expose type property in source interface

- test/init.js
- test/metadata.js
- test/s3.js
- test/utils/s3-stub.js
- test/utils/test-metadata-server.js
Added an `init` test file with root `before()` and `after()` hooks. This allows us to have a single test metadata server so we don't get transient `EADDRINUSE` errors.
Also added method to stub out `S3.getObject`. This will be deprecated shortly as there are better methods of achieving this by overloading `AWS.S3.prototype.getObject`.
> Reorganized test suite

- lib/source/s3.js
- test/s3.js
Changed the S3#status() output to return the interval rather than the timer. There are edge cases where returning the timer and outputting that data can lead to errors related to nested depth. Plus there's nothing we can actually need from the timer.
> S3#status() exposes the timer object rather than the interval

- lib/source/s3.js
- test/s3.js
Fixed bug where the default S3 parser was returning the root object parsed from the S3 body instead of the `properties` object within the root object.
We didn't have any test cases built around data that conformed to the schema so this bug was never picked up.
:thumbsup: to @jmanero-r7 for catching this one.
> Default S3 parser wasn't extracting properties object in parsed S3 body

- test/consul.js
We saw an issue on Travis CI where the test failed.
https://travis-ci.org/rapid7/propsd/builds/113500672
We now ensure that `Consul.status().updated` is set to a time that's later than when the test starts.
> Fix a timing issue in Consul plugin tests around update time.

- lib/plugin-manager.js
- lib/storage.js
- package.json
- test/plugin-manager.js
This replaces the bootstrap logic in PluginManager by listening for updates and retrying on a timer. The end result is slightly slower boot time in the worst case. If data from the EC2 metadata or S3 index are unavailable, the PluginManager waits until it gets an update form one or the other before parsing the index for additional sources.
> Fix PluginManager state machine

- test/utils/test-metadata-server.js
An extra console.log statement snuck in during a merge somewhere. This is what caused tests to spam 'Server shutting down'.
> Fix tests spamming "Server shutting down"

- README.md
- lib/plugin-manager.js
Merge properties delivered via the Config object with the metadata properties.
We'll eventually phase this out in favor of using a `File` source, but it's a good stop-gap until that's fully implemented and being polled in the `PluginManager`.
> Config properties

- test/utils/test-metadata-server.js
#57 accidentally deleted the extra log statement that was outside the loop. This removes the one inside the loop. So now there's only one "Server shutting down" statement.
> Fix tests spamming "Server shutting down" for real

- .travis.yml
- README.md
- package.json
Added coveralls and mocha clove reporter. Added report-coverage npm task that runs coverage reports and sends it to coveralls.io. Added that task to Travis if linting and tests succeed.
> Adding coveralls.io support

- lib/source/consul.js
- test/consul.js
As part of #61, the Conqueso API needs to be able to recognize that properties it's formatting are from Consul. This fixes the Consul plugin so it namespaces its generated properties by enclosing them in a "consul" object.
I've kind of viewing this as a temporary fix for now. Long term, we may want to come up with a design around an internal "properties" structure. That would allow us to define rendering rules based on property metadata.
> Fix: Namespaced Consul properties

- lib/control/v1/conqueso.js
- test/conqueso-api-v1.js
Another piece of puzzle around #61 to get the Conqueso API formatting output correctly. This translates from IP addresses as they're returned in the Consul plugin into the format defined by Conqueso. Currently on non-tagged services are supported. Tagged services will be handled in a separate pull request. There's a pending test to make sure I don't forget to do that work.
> Fix: Better Conqueso compatibility

- lib/control/v1/conqueso.js
- lib/source/consul.js
- test/conqueso-api-v1.js
- test/consul.js
This fixes #61. Services registered with Consul that are tagged with their cluster name are now exposed as `conqueso.cluster.ips=x.x.x.x` on the `/v1/conqueso` end point. Services that don't have tags are exposed with the service name as the cluster name.
> Fix: Handle tagged Conqueso IPs

- lib/plugin-manager.js
- test/data/s3/index.json
- test/plugin-manager.js
This resolves #79. The tradeoff is that the consul source needs to be enumerated in the index document in the correct location. The `PluginManager` will pick up the first occurrence of the source plugin and ignore all others so make sure that the consul plugin is positioned correctly in the index so it doesn't get overridden.
> Consul source should not be shutdown on index update

- lib/source/consul.js
- test/consul.js
This fixes #80. Usage of `Object.create(null)` has been replaced with `{}` in the Consul plugin so the `hasOwnProperty` checks in the storage engine work correctly.
> Fix: Can merge Consul plugin properties

- bin/server.js
- lib/plugin-manager.js
- lib/source/consul.js
- lib/source/metadata.js
- lib/source/s3.js
Addresses #82. Changed some logging levels to be more significant. Operations (startup, shutdown, update) should be logged as `info` from their respective source. Source status information emitted from the `PluginManager` are logged as `verbose` to maintain some separation from `debug` level logging which is fired during source polling.
I also updated the consul source so that it's logging is a little bit more meaningful.
> Fix logging levels

- lib/plugin-manager.js
- test/plugin-manager.js
This adds more tests around the PluginManager. We make sure old plugins are shut down when the index changes. We also make sure plugins are added and removed when the index changes.
> Fix: PluginManager TODO tests

- lib/control/v1/conqueso.js
- test/conqueso-api-v1.js
This fixes #90. Consul properties that have been translated into the Conqueso compatibility layer are removed from the formatted output.
> Fix: Remove translated Consul properties

- Rakefile
This resolves #83.
Instead of packing the `node` binary with the deb, we should recommend that Node be installed.
> Feature: debian package should recommend node

- test/bin/conqueso-diff
This PR resolves an issue in the `conqueso-diff` tool where values that were lists (IPs, etc.) weren't being sorted and were showing as false positives.
> Fix ordering ips in conqueso diff

- test/bin/conqueso-diff
This PR applies some transformation and sorting around properties so that we don't see false positives in the diff output.
Specifically, it sorts IP addresses (conqueso doesn't sort by default) and handles JavaScript trying to be helpful when it truncates `75.0.toString()` to `'75'`.
Archaius maps properties to Java types and reads all values from the conqueso/propsd endpoint as strings anyway, so the diffs produced by this tool truncate values with trailing zeroes that are produced by conqueso in the interest of matching values correctly.
> Fix: conqueso diff property parsing

- Rakefile
Updated the `rake deb` task to include `depends` rather than `recommends` as well as other metadata like `license`, `url`, and `description`.
Node version dependency is pulled from the project `.nvmrc` file.
> Fix: version constraint on deb recommends

- lib/source/consul.js
This PR is the first of a few to cover #103. It focuses on refactoring watcher data parsing into their own classes, prefixed with `ConquesoCompat` to indicate their intermediate status. When consul tagging is complete we can refactor that class (or create new ones that conform to the interface) to migrate to our new methodology.
This PR resolves #69 and #70.
> Fix: refactored service list watcher and service health watcher parsing into their own classes

- lib/source/consul.js
- test/conqueso-api-v1.js
- test/consul.js
Per #103, we are removing tag parsing from the Consul source completely. Later versions will likely support a `key:value` format in tags. This PR resolves #103.
> Consul source only uses service name

- test/plugin-manager.js
Travis introduces enough lag in test execution time that at least one of our tests is failing because it times out and a few others are getting close to the timeout duration. This PR bumps that to 5 seconds to give us a bit of a buffer.
> Fix: Travis test timeout latency

- lib/source/s3.js
- test/s3.js
This PR updates `_fetch()` to shut the source down and clear its properties if S3.getObject returns a NoSuchKey error. Resolves #123.
> Bug: Deleted config file doesn't trigger S3 source shutdown

- README.md
- docs/getting-started/README.md
- docs/getting-started/configuration.md
This fixes #116 . There's now a configuration guide for propsd in the "docs/getting-started" folder. The README has been updated to remove the **Configuration** section and link to the guide instead.
Currently the guide only covers installation and configuration. There are addition issues filed to cover the remaining bits like usage (see #102 for the complete scope of this project).
> Feature: Configuration guide

- lib/control/v1/conqueso.js
- test/conqueso-api-v1.js
This PR resolves #136. It only retrieves first-level properties.
For example, `/v1/conqueso/foo.bar` will return the value at `storage.properties['foo.bar']` whereas `/v1/conqueso/foo/bar` will return the value at `storage.properties['foo']['bar']`.
> Feature: Get specific property

- lib/storage.js
- test/storage-engine.js
This fixes #140. Properties are no longer cleared when sources are unregistered. Instead, we'll persist properties in memory. In memory properties will be updated when the underlying sources finish parsing and update.
> Fix: Cache properites when index rebuilds

- lib/source/common.js
- lib/source/metadata.js
- test/metadata.js
This will simplify the definition of dependency chains in the manager module.
* Remove the `Metadata#clear` method. This operation souldn't be possible.
* Move more a lot of boilerplate from the Metadata module into a common base for Source classes
> Make `Source#initialize` return a Promise

- lib/plugin-manager.js
- test/plugin-manager.js
This PR improves the way we handle source reloading. Instead of removing all sources and rebuilding the index, this adds sources if they aren't in `storage.sources` and are in the new index and removes them if they're in `storage.sources` but aren't in the new index.
This is a naive solution and can definitely be improved.
> Fix: Better logic around source reloading

- lib/plugin-manager.js
- test/plugin-manager.js
This reverts the changes introduced by #146. We accidentally introduced a bug where the sources defined in the index could get out of order. A test has been added to ensure the sources in the index stay in the order they're defined.
> Fix: Keep index sources ordered

- lib/source/common.js
- lib/source/metadata.js
- lib/source/s3.js
- test/metadata.js
- test/plugin-manager.js
- test/s3.js
* Introduces a `#state` property and named states which consolidate previous `running` and `ok`
registers.
* Introduces an additional return value for `#_fetch` to indicate that a source is `non-existent`,
not just `not-updated`. If the source was RUNNING, this signal returns the source to INITIALIZING
and notifies watchers accordingly.
Other Changes:
* Separate polling controls from initialize/shutdown
* Catch errors thrown from parsers
* Allow Sources' default Parsers to be overridden by `options.parser`
> Refactor Source to be a better defined state machine.

- lib/plugin-manager.js
- test/plugin-manager.js
This is a quick fix to prevent hourly updates to the ec2 metadata service from triggering a full source rebuild. Once we've resolved that issue, we can reimplement the metadata source as a polling source.
Ref #147
> Metadata source should only poll once

- lib/logger.js
This removes colors from logs. We're logging to STDOUT and letting users handle sending logs to terminals, files, syslog, whatever. Having colors on assumes the output is a color compatible terminal, which may not be the case.
> Fix: No colored logs

- lib/source/s3.js
- test/bin/metadata-server.js
- test/bin/s3-server.js
This allows the local test metadata and S3 servers to start. The S3 server now sets up the same configuration and logging as the metadata server.
> Fix: Startable test servers

- lib/control/v1/conqueso.js
- lib/source/consul.js
- lib/source/consul/parser.js
- test/conqueso-api-v1.js
- test/consul.js
- test/data/consul-catalog-services.json
- test/data/consul-health-service.json
- test/lib/stub/consul.js
This replaces the Consul source with a version based on polling instead of watching. This is equivalent to [the Consul source from v1.2.5](https://github.com/rapid7/propsd/blob/v1.2.5/lib/source/consul.js). We call the `/v1/catalog/services` API periodically to get a list of services, then call the `/v1/health/service/<service>` API to get a list of addresses for healthy services. Consul is polled on the same schedule as we poll S3.
> Fix: Consul polling

- lib/properties.js
- test/properties.js
This fixes a bug where propsd wouldn't start if you didn't have any properties defined statically in your config file.
> Fix: Allows layers with undefined properties

- docs/getting-started/configuration.md
- docs/getting-started/usage.md
This fixes #138. Documentation around how to configure propsd so it can use [Consul](https://www.consul.io/) for service discovery is provided. Additionally, the example `/v1/health` and `/v1/status` outputs have been updated to reflect the new metadata included in this refactor.
> Feature: Document Consul config

- lib/source/common.js
- lib/source/s3.js
- test/s3.js
- test/source-common.js
This fixes #178. The ETag for an S3 source is now explicitly cleared when a `NoSuchKey` error is returned from AWS. This ensures propsd will get properties from the source when it becomes available.
The fix applies to all polling sources. Currently, only the S3 source takes advantage of it.
> Fix: S3 ETag caching

- cookbook/recipes/default.rb
Fixes a bug where propsd is restarted every time a chef run is done because permissions are being changed from `777` to `755`.
> Let chef set the default mode on the symlink

- Buildfile
- cookbook/README.md
- cookbook/attributes/default.rb
- cookbook/files/default/propsd_ohai_plugin.rb
- cookbook/metadata.rb
- cookbook/recipes/ohai_plugin.rb
- cookbook/recipes/test.rb
This PR adds an Ohai plugin for Propsd.  This gives you access to all of the properties found in the Propsd `/properties` api from within Chef.
This plugin is optional, in-order to use it add `propsd::ohai_plugin` to a run_list.
The of the properties are available under the `node['propsd_plugin']` key.
> Add Propsd Ohai Plugin

- cookbook/files/default/propsd_ohai_plugin.rb
This change fixes the name of the Mash we are assigning values.  This
was missed in a final refactor to #186.
> Fixes Mash name

- bin/server.js
- lib/properties.js
- test/properties.js
This PR refactors the `Properties` class to never reverse internal arrays. This fixes problems where the `Properties#sources` getter and `Properties#build()` were mutating objects in place. It reverses the order in which Consul, EC2 Metadata, and static properties are loaded in `server.js`.
Resolves #189 and supersedes #192 and #196.
> Bug layer ordering reversed

- lib/source/metadata.js
Somewhere in aws-sdk@2.6 the behavior of the metadata service client changed to start raising errors for 404 responses. This change catches and suppresses those errors.
> Suppress EC2 metadata client errors for non-existent paths

- Rakefile
The `--only` flag is supported under npm 3+. Because we're pinned to LTS, we're using npm 2.x so all packages were being installed.
> Bug: Rake task packs dev dependencies on older versions of npm

- test/lib/helpers.js
- test/tokend-transformer.js
This speeds up the polling intervals for the Tokend integration tests so they run faster. We're seeing [timeout issues for some tests in Travis CI](https://travis-ci.org/rapid7/propsd/builds/164662716).
> Fix: Faster Tokend integration tests

- Gemfile
- Gemfile.lock
- README.md
- Rakefile
This PR repurposes the `:release` task to create a new Github release. Running this task requires proper repository permissions or else the task will fail.
> GitHub release task

- .gitignore
- Gemfile
This PR defines a `:cookbook` group so we can use the `--without` flag when we want to `bundle install` and not have to wait forever for `dep-selector-libgecode` to install.
> Separate cookbook and build gem dependencies

- .gitignore
- Gemfile
- Gemfile.lock
- cookbook/.kitchen.yml
- cookbook/recipes/default.rb
- cookbook/templates/default/systemd.service.erb
Currently this cookbook does not support systems that depend on systemd to start services.  
This change adds support for systemd.
> Adding support for Ubuntu 16.04 via systemd service support

- cookbook/recipes/default.rb
This PR resolves a bug where enabling a previously disabled upstart service causes chef to modify the template per this diff:
```diff
#start on (local-filesystems and net-device-up IFACE!=lo)
---
start on (local-filesystems and net-device-up IFACE!=lo)
```
This restart was causing client services to fail when attempting to access Propsd.
> Removed upstart script creation notifying service restart.

- lib/control/v1/properties.js
- lib/logger.js
- lib/util/index.js
- test/util.js
This PR adds an additional `/v1/properties/:property*` endpoint to allow specifying a single property for retrieval.
This resolves #227.
> Feature: retrieve specific property

- Buildfile
- cookbook/metadata.rb
- cookbook/recipes/default.rb
- cookbook/recipes/nodejs.rb
- cookbook/recipes/ohai_plugin.rb
- cookbook/recipes/test.rb
This PR moves away from installing Nodejs from the NodeSource repository because they don't provide earlier versions preferring, instead, to install from binary.
> Update node installation method

- lib/transformers/tokend.js
- test/tokend-transformer.js
This PR is a companion for https://github.com/rapid7/tokend/pull/106 which implements data key encryption in Tokend. It adds the `datakey` property to the  KMS payload if it exists so that Tokend can handle it.
> Feature: Add datakey field to Tokend transformer

- lib/source/metadata.js
- lib/source/metadata/parser.js
- test/metadata.js
This PR adds functionality to the `Metadata` source to retrieve information about the instance's auto-scaling group. This resolves #126.
> Feature: metadata source gets ASG info

- lib/source/metadata/parser.js
- test/data/s3/index.json
- test/data/s3/role/fake-fake.json
- test/metadata.js
Context: One of our services is going to start consuming from different queues/buckets when given "role" of "on demand" instead of the default role. This lines up fairly closely with the instance profile/role since we want to only grant access based on those.
We can use the instance profile/role for separating services.
Instance Tags would be nice but this is very straight forward first step.
> Support {{ instance:iam-role }} for indexing

- bin/server.js
- lib/source/consul.js
- lib/source/consul/parser.js
- lib/sources.js
- test/conqueso-api-v1.js
- test/consul.js
- test/lib/helpers.js
This PR removes the Consul source from being loaded by default as a `dynamic` layer. Instead, it is loaded as a regular source. In order to maintain backwards compatibility, the set of Consul properties is namespaced in the same way that it was before this change.
Resolves #223.
> Fix: Consul source should not be loaded by default

- lib/properties.js
- test/properties.js
This PR fixes a regression introduced in 4e925e4 where empty properties were assigned null rather than removed from the properties object entirely.
> Fix: empty properties are persisted as `null`.

- lib/source/metadata.js
- test/metadata.js
This PR fixes an issue where ASG retrieval is done every time the metadata source refreshes instead of caching the data.
> Fix: Metadata source requests too much data

- config/dev.json
Port 8900 produces
```
"ERROR: Aws-sdk returned the following error during the metadata service request to /latest/meta-data/placement/availability-zone: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8900}"
```
Changed to "8080" corrects the error.
> Update dev metadata port number

- bin/server.js
- config/defaults.json
- lib/source/metadata.js
This PR creates a separate config object for the `Tags` source so we can make it poll less frequently.
> Make tags source tuneable

- lib/properties.js
- lib/source/tags.js
- lib/transformers/tokend.js
- package.json
- test/properties.js
- yarn.lock
This PR resolves an issue where the `Tag` source would not nest its data in the `instance` object but instead create a new object with key `instance:tags`.
> Fix tag source is not nested

- src/lib/control/v1/conqueso.js
- src/lib/control/v1/properties.js
- src/lib/properties.js
- src/lib/transformers/tokend-client.js
- src/lib/transformers/tokend.js
- test/conqueso-api-v1.js
- test/properties.js
- test/tokend-client.js
- test/tokend-transformer.js
This bug fixes an issue where the `TokendTransformer` caches request Promises and never attempts them again. Calls to `transform` continue to use the old `Promise` which has already been resolved or rejected.
> Bug: TokendTransformer caching

- src/config/defaults.json
- src/lib/properties.js
- src/lib/transformers/tokend.js
- test/tokend-transformer.js
This PR caches responses from Tokend so we don't bust KMS API limits by doing decrypt operations  on every secret every time we hit the `/conqueso` or `/properties` endpoint.
> Fix: Add Tokend caching

- src/lib/source/common.js
- src/lib/sources.js
- test/core-api-v1.js
- test/sources.js
This change is to modify the propsd health-check.
Currently, the health-check will return with a `200` unless a source or index is in `WARNING` or `ERROR` state
However, we have seen scenarios where the health-check will return `200` when sources are in an `INITIALIZING` or `CREATING` state
These states should return a not ready Status Code
Having some sources in an error state should not stop the service from being used, however having all in error should.
Worked on with @davepgreene
> Updating the propsd health-check to reflect initialising state
